apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "csi-nas.node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    addon.vke.volcengine.com/status-check: csi-nas
{{ include "csi-nas.node.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "csi-nas.node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        addon.vke.volcengine.com/status-check: csi-nas
        {{- include "csi-nas.node.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.node.hostNetwork.enabled }}
      hostNetwork: true
      {{- end }}
      dnsPolicy: {{ .Values.node.dnsPolicy }}
      {{- if .Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.node.nodeSelector | trim | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "csi-nas.serviceAccountName" . }}
      priorityClassName: {{ .Values.node.priorityClassName }}
      {{- if .Values.publicConfig.affinity }}
      affinity:
        {{- toYaml .Values.publicConfig.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.node.tolerations }}
      tolerations:
        {{- toYaml .Values.node.tolerations | trim | nindent 8 }}
      {{- end }}
      {{- if .Values.node.volumes }}
      volumes:
        {{- toYaml .Values.node.volumes | trim | nindent 12 }}
      {{- end }}
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          image: {{ .Values.publicConfig.registry }}/{{ .Values.node.liveness.image.name }}:{{ .Values.node.liveness.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          args:
            - --csi-address=/csi/csi.sock
            - --health-port=9908
            - --probe-timeout=3s
            - --v=2
          {{- if .Values.node.liveness.resources }}
          resources:
            {{- toYaml .Values.node.liveness.resources | trim | nindent 12 }}
          {{- end }}
        - name: node-driver-registrar
          image: {{ .Values.publicConfig.registry }}/{{ .Values.node.registrar.image.name }}:{{ .Values.node.registrar.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/nas.csi.volcengine.com/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          {{- if .Values.node.registrar.resources }}
          resources:
            {{- toYaml .Values.node.registrar.resources | trim | nindent 12 }}
          {{- end }}
        - name: csi-nas-driver
          image: {{ .Values.publicConfig.registry }}/{{ .Values.node.driver.image.name }}:{{ .Values.node.driver.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          securityContext:
            privileged: true
            capabilities:
              add: [ "SYS_ADMIN" ]
            allowPrivilegeEscalation: true
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--node-id=$(NODE_ID)"
          ports:
            - containerPort: 9908
              name: healthz
              protocol: TCP
          {{- if .Values.node.driver.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.node.driver.livenessProbe | trim | nindent 12 }}
          {{- end }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: mountpoint-dir
          {{- if .Values.node.driver.resources }}
          resources:
            {{- toYaml .Values.node.driver.resources | trim | nindent 12 }}
          {{- end }}
