{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "csi-nas.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "csi-nas.labels" . | nindent 4 }}
{{- end }}