---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-nas-pvc-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: csi-nas-pv-static  # defined in csi-pv.yaml
  storageClassName: ""