---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-nas-pv-static
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  csi:
    driver: nas.csi.volcengine.com
    volumeAttributes:
      server: "100.65.230.38"
      path: "/fs-039e9a16"
    volumeHandle: pv-nas
  mountOptions:
    - nolock,tcp,noresvport
    - vers=3
