---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-nas-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: volcengine-nas # defined in csi-storageclass.yaml