---
# Source: csi-tos/templates/csinode.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-tos-node
  namespace: kube-system
  labels:
    app.kubernetes.io/name: csi-tos-node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-tos-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-tos-node
    spec:
      serviceAccount: csi-tos
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: NotIn
                    values:
                      - virtual-node
      tolerations:
        - operator: Exists
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          image: cr-cn-guilin-boe.ivolces.com/vke/livenessprobe:v0.4.1
          imagePullPolicy: Always
          args:
            - --csi-address=/csi/csi.sock
            - --health-port=9909
            - --connection-timeout=3s
            - --v=2
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: node-driver-registrar
          image: cr-cn-guilin-boe.ivolces.com/vke/csi-driver-registrar:v0.4.2
          imagePullPolicy: Always
          args:
            - --csi-address=$(ADDRESS)
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: csi-tos-driver
          image: cr-cn-guilin-boe.ivolces.com/vke/tosplugin:v0.3
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add: [ "SYS_ADMIN" ]
            allowPrivilegeEscalation: true
          args:
            - "-v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--node-id=$(NODE_ID)"
          ports:
            - containerPort: 9909
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: launcher-socket-dir
              mountPath: /tmp
              mountPropagation: "Bidirectional"
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/tos.csi.volcengine.com
            type: DirectoryOrCreate
        - name: launcher-socket-dir
          hostPath:
            path: /etc/csi-tos
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory