---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-ebs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: volcengine-ebs # defined in csi-storageclass.yaml