---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: volcengine-ebs
provisioner: ebs.csi.volcengine.com
parameters:
  type: ESSD_PL0
  fsType: ext4
  zone: ""
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate