---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csi-ebs-pvc-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: csi-ebs-pv-static  # defined in csi-pv.yaml
  storageClassName: ""