apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-snapshot-restore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-ssd
  resources:
    requests:
      storage: 20Gi
  dataSource:
    name: ebs-volume-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io