---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ebs-provisioner-binding
  labels:
{{ include "csi-ebs.common.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-ebs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-ebs-external-provisioner-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ebs-attacher-binding
  labels:
{{ include "csi-ebs.common.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-ebs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-ebs-external-attacher-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ebs-csi-resizer-role
  labels:
{{ include "csi-ebs.common.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-ebs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-ebs-external-resizer-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-ebs-csi-snapshotter-role
  labels:
{{ include "csi-ebs.common.labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "csi-ebs.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-ebs-external-snapshotter-role
  apiGroup: rbac.authorization.k8s.io