{{ if .Values.publicConfig.isPTSSDWhitelistAccount }}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-ssd
parameters:
  ChargeType: PostPaid
  type: PTSSD
provisioner: ebs.csi.volcengine.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-essd
parameters:
  ChargeType: PostPaid
  type: {{ .Values.publicConfig.ebsDiskType }}
provisioner: ebs.csi.volcengine.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{ else }}
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-ssd
parameters:
  ChargeType: PostPaid
  type: {{ .Values.publicConfig.ebsDiskType }}
provisioner: ebs.csi.volcengine.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{ end }}